// sampleProduct.ts
export const sampleProduct = {
  id: "a67cd5b8-d410-4273-afb1-7189d88230fa",
  name: "asdasddbhesdd",
  price: 0,
  discount: "",
  description: "asdasda. yoo\ngg",
  stock: 0,
  reviewCount: null,
  averageRating: null,
  images: [
    {
      id: "2c405c59-5196-4d7d-91f7-33495dc67e37",
      productId: "a67cd5b8-d410-4273-afb1-7189d88230fa",
      main: "https://i.ibb.co/Q3hNCXRz/product-main.webp",
      preview: "https://i.ibb.co/gL5BfXzF/product-preview.webp",
      thumbnail: "https://i.ibb.co/pvxybZBK/product-thumb.webp",
    },
    {
      id: "b0c39bd8-fab9-424f-afa3-eafa8207c043",
      productId: "a67cd5b8-d410-4273-afb1-7189d88230fa",
      main: "https://i.ibb.co/q3XLhLfQ/product-main.webp",
      preview: "https://i.ibb.co/Z1Hps085/product-preview.webp",
      thumbnail: "https://i.ibb.co/GQQm0qG3/product-thumb.webp",
    },
    {
      id: "26509d27-1f65-4e31-944a-c3d38b08e48e",
      productId: "a67cd5b8-d410-4273-afb1-7189d88230fa",
      main: "https://i.ibb.co/3ycGLf2G/product-main.webp",
      preview: "https://i.ibb.co/MDJbT9Qt/product-preview.webp",
      thumbnail: "https://i.ibb.co/jZj0pxbv/product-thumb.webp",
    },
  ],
  options: [
    {
      id: "64b1a7b9-ea0d-46f7-8baf-47ffcc05ca95",
      productId: "a67cd5b8-d410-4273-afb1-7189d88230fa",
      name: "Size",
      values: "S, M, L, XL, XXL, 3XL",
    },
    {
      id: "b74310a5-f59c-4dec-afd3-b1c336817f1b",
      productId: "a67cd5b8-d410-4273-afb1-7189d88230fa",
      name: "Color",
      values: "Red, Green, Blue, White",
    },
  ],
  tags: [],
  categories: [],
  collections: [],
  variants: [
    { options: "Size:S|Color:Red", stock: 0 },
    { options: "Size:S|Color:Green", stock: 0 },
    { options: "Size:S|Color:Blue", stock: 0 },
    { options: "Size:S|Color:White", stock: 0 },
    { options: "Size:M|Color:Red", stock: 0 },
    { options: "Size:M|Color:Green", stock: 0 },
    { options: "Size:M|Color:Blue", stock: 0 },
    { options: "Size:M|Color:White", stock: 0 },
    { options: "Size:L|Color:Red", stock: 0 },
    { options: "Size:L|Color:Green", stock: 0 },
    { options: "Size:L|Color:Blue", stock: 0 },
    { options: "Size:L|Color:White", stock: 0 },
    { options: "Size:XL|Color:Red", stock: 0 },
    { options: "Size:XL|Color:Green", stock: 0 },
    { options: "Size:XL|Color:Blue", stock: 0 },
    { options: "Size:XL|Color:White", stock: 0 },
    { options: "Size:XXL|Color:Red", stock: 0 },
    { options: "Size:XXL|Color:Green", stock: 0 },
    { options: "Size:XXL|Color:Blue", stock: 0 },
    { options: "Size:XXL|Color:White", stock: 0 },
    { options: "Size:3XL|Color:Red", stock: 0 },
    { options: "Size:3XL|Color:Green", stock: 0 },
    { options: "Size:3XL|Color:Blue", stock: 0 },
    { options: "Size:3XL|Color:White", stock: 0 },
  ],
};
