// PostTypeGen.js
const fs = require("fs");
const path = require("path");

// Define a consistent separator
const separator = "//" + "=".repeat(70);

// Path to your generated TS file
const filePath = path.join(__dirname, "../shared/types/PrismaTypes.ts");

// Read file content
let content = fs.readFileSync(filePath, "utf-8");

// --- Add file header ---
// Remove old header if exists
const header = `
${separator}
// Prisma Types
// Generated by prisma-generator-typescript-interfaces.
// Edited by PostTypeGen.js to modify headers and field options.
// Do not edit directly!
${separator}`;

// replace prisma-generator-typescript-interfaces header
content = content.replace("// [PrismaTypesHeader]", header);

// --- Apply direct field replacements ---
const replacements = [
  // make id and createdAt/updatedAt fields optional
  ["id:", "id?:"],
  ["Id:", "Id?:"],
  ["createdAt:", "createdAt?:"],
  ["updatedAt:", "updatedAt?:"],
];

replacements.forEach(([find, replace]) => {
  const escapedFind = find.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const regex = new RegExp(escapedFind, "g");
  content = content.replace(regex, replace);
});

// --- Replace comment-guided JsonValue conversions (///is*TYPE*) ---
content = content.replace(
  /\/\*\*\s*\n\s*\*\s*is\*([^\*]+)\*\s*\n\s*\*\s*\/\s*\n\s*([\w?]+:\s*)(JsonValue)([^\n;]*;)/g,
  function (_match, typeName, prefix, _json, suffix) {
    const cleanType = typeName.trim();
    return prefix + cleanType + suffix;
  }
);

// --- Convert multi-line block headers to single-line comments ---
content = content.replace(
  /\/\*\*\s*\n\s*\*\s*\/{59,}\s*\n\s*\*\s*(.*?)\s*\n\s*\*\s*\/{59,}\s*\n\s*\*\//g,
  function (match, title) {
    const cleaned = title.replace(/^\*?\s*\/{0,}\s*/, "").trim();
    return separator + "\n// " + cleaned + "\n" + separator + "\n";
  }
);

// Write back the modified file
fs.writeFileSync(filePath, content, "utf-8");

console.log("✅ Headers and replacements applied successfully!");
